# A workflow runs all tests and creates/updates Docker image
name: Run tests and update image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run all tests in project
        run: |
          mvn compile && mvn test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: target/site/jacoco/
          retention-days: 7
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_TOKEN }}
      - name: Build and publish updated image
        run: |
          mvn package
          reponame_lowercase=${GITHUB_REPOSITORY,,}
          image_name=$(echo ${reponame_lowercase} | cut -f2 -d/)-img
          image_tag=ghcr.io/${reponame_lowercase}/${image_name}:latest
          echo "Image tag is ${image_tag}"
          docker build . --tag ${image_tag}
          docker push ${image_tag}

  update_coverage_report:
    needs: run_tests
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/test_coverage_report.yml
